export const CONSTANTS = {
    carsPerPage: 7,
    page: 1,
    winnersPage: 1,
    winnersPerPage: 10,
    generateCars: 100,
    selectedCar: {
      id: 0,
      name: '',
      color: '',
    },
    brands: [
      'Alfa Romeo',
      'Aston Martin',
      'Audi',
      'BMW',
      'Chevrolet',
      'Chrysler',
      'Ferrari',
      'Fiat',
      'Ford',
      'Honda',
      'Hyundai',
      'Kia',
      'Lexus',
      'Mazda',
      'Mercedes-Benz',
      'Mini',
      'Mitsubishi',
      'Nissan',
      'Opel',
      'Peugeot',
      'Porsche',
      'Renault',
      'Tesla',
      'Toyota',
      'Volkswagen',
      'Volvo',
    ],
    models: [
      'Spider',
      'A6',
      'A5',
      'TT',
      'Active3',
      'Lumina',
      'Venture',
      'Cruiser',
      'Viper',
      'C-MAX',
      'Sierra',
      'Accent',
      'Spectra',
      'Aviator',
      'Capri',
      'Outlander',
    ],
  };  